import { defineArrayMember, defineField, defineType } from "sanity";
import { imageWithAlt, portableBodyOf } from "./shared";

export const page = defineType({
  name: "page",
  title: "Page",
  type: "document",
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      options: { source: "title" },
      validation: (rule) => rule.required(),
    }),
    defineField({ name: "uri", title: "URI Path", type: "string" }),
    defineField({ name: "legacyId", title: "WordPress ID", type: "number" }),
    defineField({ name: "publishedAt", title: "Published At", type: "datetime" }),
    defineField({ name: "modifiedAt", title: "Modified At", type: "datetime" }),
    defineField({ name: "excerpt", title: "Excerpt", type: "text" }),
    imageWithAlt("mainImage", "Main Image"),
    defineField({ name: "seo", title: "SEO", type: "seo" }),
    defineField({
      name: "body",
      title: "Body",
      type: "array",
      of: portableBodyOf,
    }),
    defineField({ name: "rawHtml", title: "Raw HTML (fallback)", type: "text" }),
  ],
});

export const post = defineType({
  name: "post",
  title: "Blog Post",
  type: "document",
  groups: [
    { name: "content", title: "Content", default: true },
    { name: "listing", title: "Listing & author" },
    { name: "seo", title: "SEO" },
    { name: "legacy", title: "Legacy" },
  ],
  fields: [
    defineField({
      name: "title",
      title: "Title",
      type: "string",
      group: "content",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "slug",
      title: "Slug",
      type: "slug",
      group: "content",
      options: { source: "title" },
      validation: (rule) => rule.required(),
    }),
    defineField({ name: "uri", title: "URI Path", type: "string", group: "content" }),
    defineField({
      name: "legacyId",
      title: "WordPress ID",
      type: "number",
      group: "legacy",
    }),
    defineField({
      name: "publishedAt",
      title: "Published At",
      type: "datetime",
      group: "listing",
    }),
    defineField({
      name: "modifiedAt",
      title: "Last updated",
      type: "datetime",
      group: "listing",
    }),
    defineField({
      name: "excerpt",
      title: "Excerpt",
      type: "text",
      rows: 3,
      group: "listing",
      description: "Used on blog cards (≈2 lines).",
    }),
    defineField({
      name: "categories",
      title: "Categories",
      type: "array",
      group: "listing",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "tags",
      title: "Tags",
      type: "array",
      group: "listing",
      of: [{ type: "string" }],
    }),
    defineField({
      name: "featured",
      title: "Featured on listing",
      type: "boolean",
      group: "listing",
      initialValue: false,
    }),
    defineField({
      name: "readTimeMinutes",
      title: "Read time (minutes)",
      type: "number",
      group: "listing",
    }),
    defineField({
      name: "authorName",
      title: "Author name",
      type: "string",
      group: "listing",
      initialValue: "Dr. Sandeep Bhasin",
    }),
    defineField({
      name: "authorRole",
      title: "Author role",
      type: "string",
      group: "listing",
      initialValue: "Cosmetic & Plastic Surgeon",
    }),
    imageWithAlt("authorImage", "Author photo"),
    imageWithAlt("mainImage", "Main / card image"),
    defineField({
      name: "midArticleCta",
      title: "Mid-article CTA",
      type: "object",
      group: "content",
      fields: [
        defineField({
          name: "enabled",
          type: "boolean",
          title: "Show mid-article CTA",
          initialValue: true,
        }),
        defineField({
          name: "headline",
          type: "string",
          title: "Headline",
          initialValue: "Have questions? Book a free 15-min consultation",
        }),
        defineField({
          name: "buttonLabel",
          type: "string",
          title: "Button label",
          initialValue: "Book free consultation",
        }),
      ],
    }),
    defineField({
      name: "relatedPosts",
      title: "Related articles",
      type: "array",
      group: "listing",
      of: [defineArrayMember({ type: "reference", to: [{ type: "post" }] })],
      validation: (rule) => rule.max(3),
    }),
    defineField({ name: "seo", title: "SEO", type: "seo", group: "seo" }),
    defineField({
      name: "body",
      title: "Body",
      type: "array",
      group: "content",
      of: portableBodyOf,
    }),
    defineField({
      name: "rawHtml",
      title: "Raw HTML (fallback)",
      type: "text",
      group: "legacy",
    }),
  ],
  preview: {
    select: {
      title: "title",
      subtitle: "categories.0",
      media: "mainImage",
    },
  },
});
