/**
 * Element descriptors for Blog Engine + Editorial components (ADR-016 / Phase 6.1).
 * Presentation overlays only — never mutates WordPress content.
 */

import type { ElementDescriptor } from "@/types/element-descriptor";

export const BLOG_ELEMENT_DESCRIPTORS: ElementDescriptor[] = [
  {
    id: "blog.hero.title",
    displayName: "Hero Title",
    kind: "heading",
    sectionId: "blog.hero",
    fields: [{ key: "text", label: "Title", type: "text", group: "Content" }],
    supports: { inlineEdit: true, responsive: true },
    inlineField: "text",
  },
  {
    id: "blog.hero.excerpt",
    displayName: "Hero Excerpt",
    kind: "paragraph",
    sectionId: "blog.hero",
    fields: [
      { key: "text", label: "Excerpt", type: "textarea", group: "Content" },
    ],
    supports: { inlineEdit: true },
    inlineField: "text",
  },
  {
    id: "blog.hero.image",
    displayName: "Hero Image",
    kind: "image",
    sectionId: "blog.hero",
    fields: [
      { key: "image", label: "Image", type: "media", group: "Content" },
      { key: "alt", label: "Alt text", type: "text", group: "Accessibility" },
      {
        key: "fit",
        label: "Object fit",
        type: "select",
        group: "Content",
        options: [
          { label: "Original (no crop)", value: "original" },
          { label: "Contain", value: "contain" },
          { label: "Cover (crops)", value: "cover" },
          { label: "Editorial Portrait", value: "editorial-portrait" },
          { label: "Editorial Landscape", value: "editorial-landscape" },
          { label: "Responsive auto", value: "responsive" },
        ],
      },
      {
        key: "position",
        label: "Focal position",
        type: "select",
        group: "Layout",
        options: [
          { label: "Center", value: "center" },
          { label: "Top", value: "top" },
          { label: "Bottom", value: "bottom" },
          { label: "Left", value: "left" },
          { label: "Right", value: "right" },
        ],
      },
      {
        key: "layoutVariant",
        label: "Hero layout",
        type: "select",
        group: "Layout",
        options: [
          { label: "Editorial", value: "editorial" },
          { label: "Magazine", value: "magazine" },
          { label: "Split Left", value: "split-left" },
          { label: "Split Right", value: "split-right" },
          { label: "Full Bleed", value: "full-bleed" },
          { label: "Floating Card", value: "floating-card" },
          { label: "Minimal", value: "minimal" },
          { label: "Image Focus", value: "image-focus" },
        ],
      },
      {
        key: "previewOriginal",
        label: "Preview original dimensions",
        type: "boolean",
        group: "Advanced",
      },
    ],
    supports: { replaceMedia: true, crop: true, responsive: true },
  },
  {
    id: "blog.layout.template",
    displayName: "Layout Template",
    kind: "generic",
    sectionId: "blog.presentation",
    fields: [
      {
        key: "layoutTemplateId",
        label: "Template",
        type: "select",
        group: "Content",
        options: [
          { label: "Auto", value: "" },
          { label: "Treatment Guide", value: "treatment-guide" },
          { label: "Medical Research", value: "medical-research" },
          { label: "FAQ Heavy", value: "faq-heavy" },
          { label: "Cost Guide", value: "cost-guide" },
          { label: "Before/After", value: "before-after-showcase" },
          { label: "Recovery Guide", value: "recovery-guide" },
          { label: "Long-form Editorial", value: "long-form-editorial" },
          { label: "Celebrity Health", value: "celebrity-health" },
        ],
      },
      {
        key: "spacingPreset",
        label: "Spacing",
        type: "select",
        group: "Spacing",
        options: [
          { label: "Comfortable", value: "comfortable" },
          { label: "Compact", value: "compact" },
          { label: "Luxury", value: "luxury" },
          { label: "Magazine", value: "magazine" },
          { label: "Medical", value: "medical" },
        ],
      },
    ],
    supports: {},
  },
  {
    id: "blog.preset",
    displayName: "Presentation Preset",
    kind: "generic",
    sectionId: "blog.presentation",
    fields: [
      {
        key: "editorialPreset",
        label: "Preset",
        type: "select",
        group: "Content",
        options: [
          { label: "Editorial", value: "editorial" },
          { label: "Medical Journal", value: "medical-journal" },
          { label: "Magazine", value: "magazine" },
          { label: "Luxury", value: "luxury" },
          { label: "Minimal", value: "minimal" },
        ],
      },
    ],
    supports: {},
  },
  {
    id: "blog.author.name",
    displayName: "Author Name",
    kind: "heading",
    sectionId: "blog.author",
    fields: [{ key: "text", label: "Name", type: "text", group: "Content" }],
    supports: { inlineEdit: true },
    inlineField: "text",
  },
  {
    id: "blog.author.bio",
    displayName: "Author Bio",
    kind: "paragraph",
    sectionId: "blog.author",
    fields: [
      { key: "text", label: "Bio", type: "textarea", group: "Content" },
    ],
    supports: { inlineEdit: true },
    inlineField: "text",
  },
  {
    id: "blog.section.benefits",
    displayName: "Benefits Grid",
    kind: "card",
    sectionId: "blog.semantic.benefits",
    fields: [
      { key: "enabled", label: "Enabled", type: "boolean", group: "Content" },
      {
        key: "spacing",
        label: "Spacing",
        type: "spacing",
        group: "Spacing",
        responsive: true,
      },
    ],
    supports: { animation: true, responsive: true },
  },
  {
    id: "blog.section.risks",
    displayName: "Warning Cards",
    kind: "card",
    sectionId: "blog.semantic.risks",
    fields: [
      { key: "enabled", label: "Enabled", type: "boolean", group: "Content" },
    ],
    supports: { animation: true, responsive: true },
  },
  {
    id: "blog.section.faq",
    displayName: "FAQ Accordion",
    kind: "generic",
    sectionId: "blog.semantic.faq",
    fields: [
      { key: "enabled", label: "Enabled", type: "boolean", group: "Content" },
      {
        key: "style",
        label: "Style",
        type: "select",
        group: "Content",
        options: [
          { label: "Accordion", value: "accordion" },
          { label: "List", value: "list" },
          { label: "Cards", value: "cards" },
        ],
      },
    ],
    supports: { animation: true },
  },
  {
    id: "blog.section.timeline",
    displayName: "Procedure Timeline",
    kind: "generic",
    sectionId: "blog.semantic.timeline",
    fields: [
      { key: "enabled", label: "Enabled", type: "boolean", group: "Content" },
    ],
    supports: { animation: true, responsive: true },
  },
  {
    id: "blog.section.research",
    displayName: "Research Cards",
    kind: "card",
    sectionId: "blog.semantic.research",
    fields: [
      { key: "enabled", label: "Enabled", type: "boolean", group: "Content" },
    ],
    supports: { animation: true },
  },
  {
    id: "blog.cta.heading",
    displayName: "CTA",
    kind: "generic",
    sectionId: "blog.cta",
    fields: [
      { key: "enabled", label: "Enabled", type: "boolean", group: "Content" },
      {
        key: "everySections",
        label: "Inline every N sections",
        type: "number",
        group: "Content",
        min: 0,
        max: 12,
      },
    ],
    supports: {},
  },
  {
    id: "blog.doctor.card",
    displayName: "Doctor Card",
    kind: "card",
    sectionId: "blog.doctor",
    fields: [
      { key: "enabled", label: "Enabled", type: "boolean", group: "Content" },
      { key: "heading", label: "Heading", type: "text", group: "Content" },
      { key: "photo", label: "Photo", type: "media", group: "Content" },
    ],
    supports: { replaceMedia: true, responsive: true },
  },
  {
    id: "blog.related.heading",
    displayName: "Related Posts",
    kind: "heading",
    sectionId: "blog.related",
    fields: [
      { key: "text", label: "Heading", type: "text", group: "Content" },
    ],
    supports: { inlineEdit: true },
    inlineField: "text",
  },
  {
    id: "blog.content.tableStyle",
    displayName: "Table Style",
    kind: "generic",
    sectionId: "blog.content",
    fields: [
      {
        key: "tableStyle",
        label: "Style",
        type: "select",
        group: "Content",
        options: [
          { label: "Minimal", value: "minimal" },
          { label: "Card", value: "card" },
          { label: "Professional", value: "professional" },
        ],
      },
    ],
    supports: {},
  },
  {
    id: "blog.content.imageStyle",
    displayName: "Image Style",
    kind: "generic",
    sectionId: "blog.content",
    fields: [
      {
        key: "imageStyle",
        label: "Style",
        type: "select",
        group: "Content",
        options: [
          { label: "Rounded", value: "rounded" },
          { label: "Shadow", value: "shadow" },
          { label: "Editorial", value: "editorial" },
          { label: "Borderless", value: "borderless" },
        ],
      },
    ],
    supports: { replaceMedia: true, crop: true },
  },
  {
    id: "blog.toc",
    displayName: "Table of Contents",
    kind: "generic",
    sectionId: "blog.sidebar",
    fields: [
      { key: "enabled", label: "Enabled", type: "boolean", group: "Content" },
    ],
    supports: {},
  },
  {
    id: "blog.sidebar.layout",
    displayName: "Sidebar",
    kind: "generic",
    sectionId: "blog.sidebar",
    fields: [
      {
        key: "widgets",
        label: "Widgets",
        type: "json",
        group: "Content",
      },
    ],
    supports: { reorder: true },
  },
  {
    id: "blog.typography",
    displayName: "Typography",
    kind: "generic",
    sectionId: "blog.presentation",
    fields: [
      {
        key: "headingStyle",
        label: "Heading style",
        type: "select",
        group: "Typography",
        options: [
          { label: "Editorial", value: "editorial" },
          { label: "Bold", value: "bold" },
          { label: "Quiet", value: "quiet" },
        ],
      },
      {
        key: "readingWidth",
        label: "Reading width",
        type: "select",
        group: "Typography",
        options: [
          { label: "Article", value: "article" },
          { label: "Editorial", value: "editorial" },
          { label: "Wide", value: "wide" },
        ],
      },
    ],
    supports: { responsive: true },
  },
];
